package auth

import (
	_ "embed"
	"html/template"
	"strings"
)

// The branded mail layout: logo and wordmark, a white card on the warm background, the
// login code in a green box and one button. Mail clients ignore <style> blocks and web
// fonts, so the markup is tables with inline styles and the headings fall back from
// Fraunces to Georgia. The logo travels inline (Content-ID) so it shows even where remote
// images are blocked.

//go:embed mail-logo.png
var mailLogo []byte // generated by mobile/scripts/gen-icons.mjs

const mailLogoCID = "logo@stallfunk"

// MailContent is the text of a branded mail. Message renders it as plain text and HTML
// from the same fields, so both parts always say the same.
type MailContent struct {
	Preheader string   // preview line in the inbox list (HTML only)
	Heading   string   // e.g. "Dein Anmeldecode"
	Intro     []string // paragraphs above the code and the button
	Code      string   // optional, shown large (e.g. "123 456")
	Lead      string   // optional paragraph right above the button (HTML only)
	Button    string   // optional button label
	ButtonURL string   // https link of the button
	AppLink   string   // stallfunk:// link, plain text only (mail clients drop custom schemes from HTML)
	Outro     []string // paragraphs below the button
	Note      string   // small print at the end of the card
}

// Message renders c as a mail with a plain-text and an HTML part.
func (c MailContent) Message(to, subject string) (Message, error) {
	var html strings.Builder
	if err := mailTmpl.Execute(&html, c); err != nil {
		return Message{}, err
	}
	return Message{To: to, Subject: subject, Body: c.text(), HTML: html.String()}, nil
}

func (c MailContent) text() string {
	var b strings.Builder
	b.WriteString(c.Heading + "\n\n")
	for _, p := range c.Intro {
		b.WriteString(p + "\n\n")
	}
	if c.Code != "" {
		b.WriteString(c.Code + "\n\n")
	}
	// Lead talks about the button, so the text part uses its own wording for the links.
	if c.AppLink != "" {
		b.WriteString("Oder melde dich direkt an:\n" + c.AppLink + "\n\n")
	}
	if c.ButtonURL != "" {
		label := c.Button
		if c.AppLink != "" {
			label = "Falls sich die App nicht öffnet, nutze diesen Link auf dem Gerät mit der App"
		}
		b.WriteString(label + ":\n" + c.ButtonURL + "\n\n")
	}
	for _, p := range c.Outro {
		b.WriteString(p + "\n\n")
	}
	if c.Note != "" {
		b.WriteString(c.Note + "\n\n")
	}
	b.WriteString("-- \nStallfunk, die App für die Stallgasse\n")
	return b.String()
}

// Colors and fonts from docs/design-system.md.
var mailTmpl = template.Must(template.New("mail").Funcs(template.FuncMap{
	// Only https links become buttons; anything else stays plain text in the mail.
	"safeURL": func(u string) template.URL {
		if strings.HasPrefix(u, "https://") {
			return template.URL(u)
		}
		return ""
	},
}).Parse(`<!doctype html>
<html lang="de">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light">
<meta name="supported-color-schemes" content="light">
<title>{{.Heading}}</title>
</head>
<body style="margin:0;padding:0;background-color:#f6f4ee;">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:#f6f4ee;">{{.Preheader}}</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#f6f4ee;">
<tr><td align="center" style="padding:32px 16px;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:480px;">
<tr><td style="padding:0 4px 20px 4px;">
<table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>
<td style="vertical-align:middle;"><img src="cid:` + mailLogoCID + `" width="44" height="44" alt="" style="display:block;border:0;border-radius:11px;"></td>
<td style="vertical-align:middle;padding-left:12px;font-family:Fraunces,Georgia,'Times New Roman',serif;font-size:22px;font-weight:600;color:#1c3a27;">Stallfunk</td>
</tr></table>
</td></tr>
<tr><td style="background-color:#ffffff;border:1px solid #e7e2d9;border-radius:20px;padding:32px 28px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:24px;color:#1c1917;">
<h1 style="margin:0 0 16px 0;font-family:Fraunces,Georgia,'Times New Roman',serif;font-size:26px;line-height:32px;font-weight:600;color:#1c1917;">{{.Heading}}</h1>
{{range .Intro}}<p style="margin:0 0 16px 0;">{{.}}</p>
{{end}}{{if .Code}}<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 24px 0;"><tr>
<td align="center" style="background-color:#e3efe6;border-radius:14px;padding:18px 12px;font-family:'SF Mono',Menlo,Consolas,'Courier New',monospace;font-size:34px;line-height:40px;font-weight:700;letter-spacing:6px;color:#1c3a27;">{{.Code}}</td>
</tr></table>
{{end}}{{if and .Lead (safeURL .ButtonURL)}}<p style="margin:0 0 16px 0;">{{.Lead}}</p>
{{end}}{{with safeURL .ButtonURL}}<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 24px 0;"><tr>
<td align="center" style="background-color:#2d5a3d;border-radius:12px;">
<a href="{{.}}" style="display:block;padding:14px 20px;font-size:16px;font-weight:600;color:#ffffff;text-decoration:none;">{{$.Button}}</a>
</td></tr></table>
{{end}}{{range .Outro}}<p style="margin:0 0 16px 0;">{{.}}</p>
{{end}}{{if .Note}}<p style="margin:8px 0 0 0;padding-top:16px;border-top:1px solid #f0ebe1;font-size:13px;line-height:20px;color:#6b6560;">{{.Note}}</p>
{{end}}</td></tr>
<tr><td align="center" style="padding:20px 8px 0 8px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:12px;line-height:18px;color:#6b6560;">
Stallfunk, die App für die Stallgasse
</td></tr>
</table>
</td></tr>
</table>
</body>
</html>
`))
