#!/usr/bin/env node
// Generates mobile/lib/consent-legal-texts.ts from docs/legal/*.md.
// The Markdown files are the single source of truth; the app bundles them as strings.
//
//   node scripts/gen-legal.mjs           write the TS module
//   node scripts/gen-legal.mjs --check   exit 1 if the module is out of date (CI, tests)

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
export const OUTPUT = join(root, "mobile", "lib", "consent-legal-texts.ts");

const SOURCES = [
  { name: "PRIVACY_MD", file: join(root, "docs", "legal", "datenschutz.md") },
];

/** "**Textversion:** 2026-09-30" -> "2026-09-30" */
export function versionOf(markdown) {
  const m = /^\*\*Textversion:\*\*\s*(\S+)\s*$/m.exec(markdown);
  if (!m) throw new Error("no '**Textversion:** <version>' line found");
  return m[1];
}

export function render() {
  const texts = SOURCES.map((s) => ({ ...s, text: readFileSync(s.file, "utf8").replace(/\r\n/g, "\n") }));
  const versions = new Set(texts.map((t) => versionOf(t.text)));
  if (versions.size !== 1) throw new Error(`legal texts have different versions: ${[...versions].join(", ")}`);
  const [version] = versions;
  const lines = [
    "// GENERATED by scripts/gen-legal.mjs from docs/legal/*.md. Do not edit; edit the Markdown and run",
    "//   node scripts/gen-legal.mjs",
    "// (lib/consent-legal.test.ts fails while this file is out of date).",
    "",
    `export const LEGAL_TEXT_VERSION = ${JSON.stringify(version)};`,
    "",
  ];
  for (const t of texts) {
    lines.push(`export const ${t.name} = ${JSON.stringify(t.text)};`, "");
  }
  return lines.join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = render();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(OUTPUT, "utf8");
    } catch {
      // missing counts as out of date
    }
    if (current !== next) {
      console.error("mobile/lib/consent-legal-texts.ts is out of date: run node scripts/gen-legal.mjs");
      process.exit(1);
    }
  } else {
    writeFileSync(OUTPUT, next);
    console.log(`wrote ${OUTPUT}`);
  }
}
